### PR TITLE
[WIP] Redux workshop 2

### PR DESCRIPTION
**Pull request by e-schultz**
Getting to the starting point of workshop-2.

### CODE REVIEW

**Comment by e-schultz** [comment]
@bennett000 @winkerVSbecks 

Thinking of having this be the starting of the second break-point: Task add/edit/mark/delete hooked up, but not using the API yet.

Goals of building up from this stage:
* Task service to consume API
* Refactor action creators to use task service
* Add auth service (maybe)
* Add login/logout functionality

So general flow would be:
* workshop-0  - build out a bunch of the dumb components and hookup kitchen sink
* workshop-1  - flesh out the containers, and hookup actions/reducers/etc 
* workshop-2 - starting from here, and build out the API services and auth

Also working on some instructions, and some 'instructor-notes' of how to approach it.

**Comment by winkerVSbecks** [comment]
@e-schultz That looks like a good plan to me

**Comment by bennett000** [comment]
This is going to be great.

**Comment by e-schultz** [comment]
closing PR, made some orphan branches for workshop stuff.

**Pull request closed without merging**
