### PR TITLE
feat: Add shout pipe exercise

### PR DESCRIPTION
**Pull request by e-schultz**
* Create 1.0 - Simple shout
* Create 1.1 - Expand on shout to expect an argument

### CODE REVIEW

**Comment by e-schultz** [comment]
@igor-ka @winkerVSbecks @bennett000 how's this look for a start/format for the exercises?

**Comment by winkerVSbecks** [comment]
LGTM :+1:

**Comment by igor-ka** [comment]
@e-schultz LGTM too
basically follows the structure we discussed, really like the comments interspersed all over as well.
:shipit: unless you want @bennett000 to have a look too

**Comment by igor-ka** [comment]
@e-schultz one more thing, I kinda like `live-server` better than `http-server`

**Comment by e-schultz** [comment]
updated to recommend live-server instead.

**Pull request merged**
