### PR TITLE
Add HostBinding section to book

### PR DESCRIPTION
**Pull request by smithad15**
Connected to #742 

Should be merged after #773 so that the page order can be correct in `SUMMARY.md`

### CODE REVIEW

**Comment by bennett000** [comment]
@smithad15 overall, this LGTM.  I was thinking about mentioning something on @alanthai 's PR about being a little bit more explicit about what exactly a host element is, especially in with respect to `@Component` directives.

What do you two think?

**Comment by smithad15** [comment]
I think a bit more clarification on what a host element is would be a good thing to have. It should probably either go in the _HostListener_ section or the _Creating an Attribute Directive_ section. I can add that as a separate PR or merge it into this one depending on your preference.

**Comment by smithad15** [comment]
Host element explanation has been added. Should be GTG barring any requested changes.

**Comment by bennett000** [comment]
nice and straightforward, LGTM :shipit:

**Pull request merged**
