### PR TITLE
Update Dependency Injection Examples

### PR DESCRIPTION
**Pull request by watrool**
Connected to https://github.com/rangle/ngCourse2/issues/744.

### CODE REVIEW

**Comment by bennett000** [comment]
This certainly does seem more real world.  It's also reasonably agnostic.  I mention this because when we first wrote the DI section @igor-ka really wanted us to use something abstract and removed from frameworks for the _description_ part of the DI chapter.

I'm thinking we might want to keep the text using Hamburger which is completely abstract and _additionally_ provide the chat example that @watrool wrote as an example real world use case.

**Comment by watrool** [comment]
@bennett000 it makes sense to use agnostic example to explain DI that apart from any framework and `Hamburger` is indeed an abstract example. So for this PR, how should we format the two examples: `Hamburger` and `ChatWidget`? Do we need to create a new section "Real world example" under DI?

**Comment by bennett000** [comment]
@watrool the easiest way to split this is probably to use your new examples for everything under `di/angular2` and for the earlier parts keep `Hamburger`

**Comment by watrool** [comment]
@bennett000 I have done the change in 8fe70ec.

**Comment by bennett000** [comment]
:shipit:

**Pull request merged**
