### PR TITLE
Add Architecture outline

### LINKED ISSUE #180: Outline for Webinar Sign Up: Architecture
raft of Outline for Webinar Signup from April 11 Online Training Discussion
"Amazing Angular 2 Architecture - ...."

https://docs.google.com/document/d/19o5H_yOB5_08r4bbT67Y3S-u4hVz6U0l6_boaUSqzmA/edit

Acceptance Criteria:

- Overview, Objective, Target Audience, Assumed Audience Knowledge, What the Audience Member will learn:
- A description of this webinar to which marketing can apply their marketing touch.
- This is not the same as the outline for the presenter notes.
- Detailed enough that participants will want to sign up for the webinar.
- General enough that we can adjust the content as needed when we're writing it.
- Here is an example of what we have posted in the past for ad-hoc webinars: http://go.rangle.io/webinar-intro-to-angular2-components 
http://go.rangle.io/webinar-intro-to-react-native

### PR DESCRIPTION
**Pull request by bertrandk**
Closes #180 

This is essential a vague and verbose way of saying "Redux" but hey, let me know if this is what you had in mind @bennett000 or @e-schultz.

### CODE REVIEW

**Comment by e-schultz** [comment]
Redux is a part of it, but I was seeing architecture also touching on things that can be applicable outside of redux like:

* containers vs presentational components
* passing callbacks down vs emitting events up
* thinking in components
* building out more robust services layer (ie: abstractions on-top of HTTP)

Redux can fit into a few of those aspects

**Comment by bertrandk** [comment]
@e-schultz Added bit about services. Thinking of what to call "passing callbacks down vs emitting events up". The container stuff seems in conflict with the components webinar. @SethDavenport, can you advise?

**Comment by danielfigueiredo** [comment]
Input callback vs Output events seems to be a great topic @e-schultz

**Comment by bertrandk** [comment]
@e-schultz @danielfigueiredo Added callbacks down vs. events up.

**Pull request merged**
