### PR TITLE
Update examples in Components section

### PR DESCRIPTION
**Pull request by watrool**
Connected to https://github.com/rangle/ngCourse2/issues/744.

### CODE REVIEW

**Comment by watrool** [comment]
@bennett000 This [Projection](https://angular-2-training-book.rangle.io/handout/components/projection.html) part seems lacking necessary details, do we need to further elaborate on the example and `ng-content`?

**Comment by bennett000** [comment]
@watrool yes I think some elaboration would be great.  I know @winkerVSbecks is writing a blog post about this, it's in our blogs repo.  You might be able to paraphrase some of Varun's work.

**Comment by winkerVSbecks** [comment]
@bennett000 @watrool There are two posts:
- mine is more generally about flat components https://github.com/rangle/blogs/pull/91
- Evan has a detailed one about projection: https://github.com/rangle/blogs/pull/76

**Comment by watrool** [comment]
@bennett000 I have created a issue for projection: https://github.com/rangle/ngCourse2/issues/792, so can you merge this PR if there is no other problems?

**Comment by bennett000** [comment]
Based on #792 being another task this LGTM :shipit:

**Pull request merged**
