### PR TITLE
Require login to access Todo features (in progress)

### PR DESCRIPTION
**Pull request by grough**
Add Login component and AuthService, which checks against a hard coded user/password for now. Session state is kept in local storage. This should be expanded to use a remote auth service - not certain if this is supported by ngcourse-api currently.

This uses the `@CanActivate` router hook decorator to limit access to Todo features. I am looking for feedback on how Observables can be incorporated and related to course content since that topic was mentioned in the [Trello card](https://trello.com/c/teaSrnio/93-login).

### CODE REVIEW

**Comment by joehandlebar** [comment]
hey @gavin when I click on 'logout' the grid of tasks don't disappear :confounded:

**Comment by grough** [comment]
@joehandlebar that's due to the issue we were talking about in #angular2-training. I'm going to take another look at the routes based on your suggestion

**Comment by e-schultz** [comment]
@joehandlebar @grough does PR#81 make this PR obsolete?

**Comment by joehandlebar** [comment]
@e-schultz yup

**Comment by e-schultz** [comment]
Closing because #81 covers this

**Pull request closed without merging**
